language: python
sudo: false

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

before_install:
    - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
    - mkdir $HOME/.buildout
    - echo "[buildout]" > $HOME/.buildout/default.cfg
    - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
    - echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
    - echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg

matrix:
    include:
        - python: "2.7"
          env: TOXENV=lint-py27,docs
        - python: "3.6"
          env: TOXENV=lint-py36,docs
        - python: "2.7"
          env: TOXENV=py27-packagetests
        - python: "3.4"
          env: TOXENV=py34-packagetests
        - python: "3.5"
          env: TOXENV=py35-packagetests
        - python: "3.6"
          env: TOXENV=py36-packagetests
        - python: "pypy"
          env: TOXENV=pypy-packagetests
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-4.3-template-addon
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.0-template-addon
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.1-template-addon
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-4.3-template-addon_content_type
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.0-template-addon_content_type
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.1-template-addon_content_type
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-4.3-template-addon_theme
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.0-template-addon_theme
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.1-template-addon_theme
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-4.3-template-theme_package
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.0-template-theme_package
        - python: "2.7"
          env: TOXENV=py27-skeletontests-Plone-5.1-template-theme_package

install:
    - travis_retry pip install -U tox coveralls coverage

before_script:
  - export DISPLAY=:99.0
  - export VERBOSE=true
  - sh -e /etc/init.d/xvfb start

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

after_script:
  - sh -e /etc/init.d/xvfb stop

notifications:
  email:
    recipients:
      - travis-reports@plone.com
      - {author}
    on_success: change
    on_failure: change
